### ISSUE TITLE
Update dependency to Alamofire 5.0.0

### ISSUE THREAD

**Issue by LaurentiuUngur** [cloudinary/cloudinary_ios#218]
Right now Cloudinary is based on Alamofire 4.8.x version. If you have another pod using Alamofire 5.x version, there's a dependency conflict raised by Cocoapods.

**Comment by Sethmr** [comment]
This is a long awaited upgrade. Please support this as soon as possible.

**Comment by roeeba** [comment]
Hi @LaurentiuUngur, @Sethmr. The reason we've yet to work on this one is that Alamofire 5.0.0 is currently in beta. That sais, as it's in beta for some time now, we've decided to work on our own beta that will use this version. We aim to deploy it within the next few weeks. We'll update here once available.

**Comment by roeeba** [comment]
Thanks for the clarification, @Sethmr. We'll update as soon as there will be any progress.

**Comment by Sethmr** [comment]
@roeeba https://github.com/Alamofire/Alamofire/releases ... you were waiting for this version. Here it is.

**Comment by AnthonyMillerSF** [comment]
You guys shouldn't even be using Alamofire at all. #212 
It doesn't make sense for a framework to be pulling in 3rd party dependencies like this. This issue is one example of why. 

It is not that difficult to just use NSURLSession. I like using Alamofire too in my projects sometimes, but third party dependencies shouldn't have large transitive dependencies like this.

**Comment by Sethmr** [comment]
If another framework decided to do the same thing, I would have to pick between the frameworks or use potentially bug infested versions of a framework to ensure both SDKs use the same version of alamofire. This is a very clunky solution for your entire userbase.

**Comment by shirlymanor** [comment]
@AnthonyMillerSF right, we are working on a version without alamofire. however, we can't provide an ETA yet.
We will update as soon as we will have an ETA.

**Comment by albertodebortoli** [comment]
@shirlymanor this has all of a sudden become a blocker for us since we had to update to Alamofire 5.0.2 to only later (too late!) realize that Cloudinary has it as a dependency.

@AnthonyMillerSF is very much correct, and you shouldn't be using Alamofire, which I imagine it to be an issue for some of your paying clients.

Can you please give us an update, we are now not able to run `pod install` and a rollback of our code is very, _very_ undesired.

**Comment by shirlymanor** [comment]
@albertodebortoli @AnthonyMillerSF 
Unfortunately, we can't provide an ETA for a version without alamofire.
We do have a working branch with Alamofire 5.0 as a workaround. It has some issues:
1. It's not an official release. 
2. It does not support background uploads (since Alamofire 5 dropped background support).

If you are willing to test it out:
https://github.com/cloudinary/cloudinary_ios/tree/feature/bump-alamofire-5.0.0

Please let us know any feedback!

**Comment by albertodebortoli** [comment]
Thanks @shirlymanor, we ventured on a journey to fork the repo and use the branch you provided.

A note for the community facing the same problem: in order for the tests to pass, you have to update the configuration in `NetworkBaseTest.swift` to `cloudinary://<API_KEY>:<API_SECRET>@<CLOUD_NAME>`.
Our master (https://github.com/justeat/cloudinary_ios) is working just fine with Alamofire 5 but the podspec has been published to our private specs repo.

**Comment by shirlymanor** [comment]
@albertodebortoli Thak you for the feedback! we will check it out.

**Comment by AnthonyMillerSF** [comment]
Thanks for all the updates @shirlymanor. Really excited to hear you're removing the Alamofire dependency eventually! Can't wait!

**Comment by RonKliffer** [comment]
@shirlymanor Any updates on an ETA? We are currently blocked because of this dependency

**Comment by Auralien** [comment]
@shirlymanor we would really appreciate an update with Alamofire 5 support.

**Comment by shirlymanor** [comment]
We are actively working on it right now. will provide ETA soon.

**Comment by shirlymanor** [comment]
Hey, we published a beta release without alamofire -https://github.com/cloudinary/cloudinary_ios/releases/tag/2.9.0-beta.2
Can you please try it out and let us know any feedback?
