### ISSUE TITLE
Download all images from Cloudinary

### ISSUE THREAD

**Issue by prasadkumbar** [cloudinary/cloudinary_ios#221]
Hi,

I'm facing one problem here. After uploading images into Cloudnary i need to download what and all i have uploaded. 

Can anyone help me for this, like Code for downloading all images with particular Size and Width to UIImageView.

Thanks in advance.

**Comment by shirlymanor** [comment]
You can get the list of all your resources by using our admin API. unfortunately, Admin-API is not supported for IOS SDK since its a server-side API.
You could, though, use any of the languages offered in the following link:
http://cloudinary.com/documentation/admin_api#list_all_images

Best solution will be to set up a Javascript or Ruby-On-Rails env (unless you already have a running server) and maintain your resources from there.

After getting the list of public ids you can get the URL with transformation:

```
let transformation = CLDTransformation().setWidth(100).setHeight(150).setCrop(.crop)
let url = cloudinary.createUrl().setTransformation(transformation).generate(<public-id-from the list>)
```

**Comment by SreekanthGudisi** [comment]
Hi,

I have done Project. You can find the source code from the below link. 
[https://github.com/SreekanthGudisi/Cloudinary-Upload-and-Download-Images](Source Code For Uploading and Downloading)
