### ISSUE TITLE
Unable to destroy an image

### ISSUE THREAD

**Issue by thierrybucco** [cloudinary/cloudinary_ios#380]
I am unable to destroy an image by doing this call:

cloudinary.createManagementApi().destroy("publicID")

I get this error:

Missing required parameter - signature

What should I do?

**Comment by esguerrat** [comment]
@thierrybucco According to the error message you are receiving and the code I see that you shared, you are missing the signature, which is a required parameter.

The best practice is to create a signature on the backend, server-side. The reason is that you don't want your API secret to be publicly exposed in your mobile application.

You can find information on our backend SDKs here: https://cloudinary.com/documentation/backend_sdks
