### ISSUE TITLE
Is there a way to pull all videos using folder name from cloudinary

### ISSUE THREAD

**Issue by anweshannu** [cloudinary/cloudinary_ios#437]
#Question

Is there are ways to pull videos using tags or folder from cloudinary

**Comment by igy** [comment]
Hi,
If you have questions about Cloudinary's APIs and services, may I ask you to please use our support site at https://support.cloudinary.com/, rather than filing issues against the SDK code?

There's a guide here for our Admin and Search API methods:
https://cloudinary.com/documentation/admin_api#get_resources
https://cloudinary.com/documentation/search_method

However, these cannot be called from client devices without a server-side component because the API methods require account credentials to be provided for authentication. 
For an iOS app, you'd need your server to call the API or manage your database, and then provide the details to the iOS app via your own API

Thanks,
Stephen
