### ISSUE TITLE
Cloudinary Integration Walkthrough

### ISSUE THREAD

**Issue by bmurtagh** [cloudinary/cloudinary_ios#7]
Hello,

I came across the Cloundinary API and signed up for an account to begin building an app. I think the API will accomplish one of the proposed features for our application, but I was wondering if there was a more complete, step-by-step tutorial for implementing the API into a new project/workspace at least for a single-view application. Any direction or advice is appreciated.

**Comment by nadavofi** [comment]
The [readme file](https://github.com/cloudinary/cloudinary_ios/blob/master/README.md#cloudinary-ios-sdk) in the git repository contains setup instructions as well as some basic code examples.
It's on our road map to offer a  sample-project in order to provide a better starting point to our users.
If you have a specific question, don't hesitate to shoot us a [support ticket](http://support.cloudinary.com/hc/en-us/requests/new).
