### ISSUE TITLE
Using url2png addon through cloudinary-ios

### ISSUE THREAD

**Issue by chunyanglin** [cloudinary/cloudinary_ios#9]
Not sure how can I use url2png add on through cloudinary. Even I changed type field to url2png, application is getting error code from server.

Is there any advanced guide or reference code part. It seems sever does not filter new addon on server.

Looking forward to getting news in time.

Thank,

**Comment by taragano** [comment]
I'm very sorry for the late response.

The URL2PNG add-on has its own quotas, therefore in order to avoid abuse to your account the request must be authenticated. Either via the `explicit` API by using signed URLs. Note that both options require a server-side because the signature is based on your account's `api_secret` which is very recommended to not be included in your client-side code.
